
run	: 	solution2
	./solution2

solution1	: solution1.c
	gcc -Wall -Wextra -o solution1 solution1.c

solution2	: solution2.c
	gcc -Wall -Wextra -o solution2 solution2.c

clean	:
	rm -f solution1 solution2
